name: jaguar_example_https
version: 2.2.1
description: Example showing how to use HTTPs with Jaguar
homepage: https://github.com/jaguar-examples/https
authors:
  - Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  jaguar: ^2.2.6

executable:
  jaguar_example_https: server